// <auto-generated />
namespace OpsPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initdata07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initdata07));
        
        string IMigrationMetadata.Id
        {
            get { return "201607290554386_Initdata07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
